/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb
 
 */

import Foundation

extension CardIds.Secrets {
    static let arenaExcludes = [
        Hunter.Snipe
    ]
    
    static let arenaOnly = [
        Paladin.HandOfSalvation
    ]

    static let fastCombat: [MultiIdCard] = [
        Hunter.FreezingTrap,
        Hunter.ExplosiveTrap,
        Hunter.Misdirection,
        Paladin.NobleSacrifice,
        Mage.Vaporize
    ]

    // Secrets that trigger when the opponent plays a minion. Only one secret triggers per
    // event, so if one of these goes off the others were not given a chance to.
    static let minionPlayed: [MultiIdCard] = [
        Hunter.BargainBin,
        Hunter.HiddenCache,
        Hunter.Snipe,
        Hunter.Zombeeees,
        Mage.ExplosiveRunes,
        Mage.FrozenClone,
        Mage.MirrorEntity,
        Mage.Objection,
        Mage.PotionOfPolymorph,
        Paladin.Repentance,
        Rogue.Ambush,
        Rogue.Kidnap
    ]

    static let all = Hunter.All + Mage.All + Paladin.All + Rogue.All
    
    static func getSecretMultiIdCard(_ id: String) -> MultiIdCard? {
        all.first(where: { m in m.ids.contains(id) })
    }
}
